import React from 'react';
import './Standalone.css';

export function TermsOfUsage() {
  return (
    <div className="standalone-container">
      <h1 className="standalone-title">Terms of Usage</h1>
      <div className="standalone-content">
        <p>By accessing or using OrbWeather, you agree to be bound by these Terms of Usage. If you disagree with any part of the terms, then you do not have permission to access the application.</p>
        
        <h3>1. Service Description</h3>
        <p>OrbWeather is a weather dashboard application that provides localized weather forecasts, air quality indices, and astronomical data. The data is sourced from third-party providers (Open-Meteo) and is intended for general informational purposes only.</p>

        <h3>2. Disclaimer of Accuracy</h3>
        <p>The weather data and predictions presented in OrbWeather are generated by meteorological models. While we strive for accuracy, weather is inherently unpredictable. <strong>OrbWeather makes no guarantees regarding the absolute accuracy, reliability, or completeness of the data provided.</strong></p>
        
        <div style={{ padding: '16px', background: 'rgba(239, 68, 68, 0.1)', borderLeft: '4px solid #ef4444', borderRadius: '8px', margin: '24px 0', color: 'var(--text-primary)' }}>
          <strong>Critical Safety Warning:</strong> Do not rely solely on OrbWeather for critical decisions relating to personal safety, severe weather planning, or emergency situations. Always consult official local weather advisory services (such as the National Weather Service) for warnings and alerts.
        </div>

        <h3>3. Acceptable Use</h3>
        <p>You agree not to use OrbWeather in any way that causes, or may cause, damage to the application or impairment of the availability or accessibility of the service. Automated scraping or aggressive polling of the application's underlying data sources is strictly prohibited.</p>

        <h3>4. Modifications</h3>
        <p>We reserve the right to modify or replace these Terms at any time. Your continued use of the application following the posting of any changes constitutes acceptance of those changes.</p>
      </div>
    </div>
  );
}
